### PR TITLE
PLAT-4237 iOS - Allow OEMs to store commit pointer on wearable

### PR DESCRIPTION
**Pull request by alex-moc**
IPaymentDeviceConnector protocol expanded with getDeviceLastCommitId, setDeviceLastCommitId.
Added unit tests.

### CODE REVIEW

**Comment by alex-moc** [comment]
I have added new fake target FitpaySDKTestHost for Keychain testing. This target requires signin. I use new provision profile "FitpaySDKTestHost Ad Hoc" for signin. Looks like that Travis require this profile too.

**Comment by alex-moc** [comment]
[FitpaySDKTestsHost_Ad_Hoc.mobileprovision.zip](https://github.com/fitpay/fitpay-ios-sdk/files/1582300/FitpaySDKTestsHost_Ad_Hoc.mobileprovision.zip)

**Comment by Clark73** [comment]
@alex-moc Is travis not having this profile the cause of the failing build?

**Comment by alex-moc** [comment]
@Clark73 Yes, error is occurred when new target must be signed.

**Pull request merged**
