### PR TITLE
Added carthage support.

### PR DESCRIPTION
**Pull request by walkline**

### CODE REVIEW

**Comment by daver234** [comment]
Is this branch current with Master?  I'm using Carthage but Master doesn't support Carthage it appears.

**Comment by skynet67** [comment]
@daver234 Not yet. After accepting PR it should be merged into develop.

**Comment by daver234** [comment]
What is the rough timing on the PR accept?

**Comment by ssteveli** [comment]
@rossgabay will have that information on PR timing, it's under review.

**Comment by walkline** [comment]
@daver234 If you want to try it now then you can try use carthage with this branch.
Just add following line in Cartfile:
`github "fitpay/fitpay-ios-sdk" "carthage"`

**Comment by daver234** [comment]
ok thanks.  Please comment here again when it is merged. Thanks.

**Comment by rossgabay** [comment]
@daver234 , this PR has now been merged. If you have any further questions/issues please reach out to me/Brad via email.

**Comment by daver234** [comment]
So this is merged to the develop branch?

**Comment by rossgabay** [comment]
@daver234  - yes

**Comment by daver234** [comment]
Thanks.

**Pull request merged**
