### PR TITLE
Updated pods and Carthage dependencies(Alamofire, AlamofireObjectMapp…

### PR DESCRIPTION
**Pull request by alex-moc**
…er, ObjectMapper, RxSwift) to last versions.

### CODE REVIEW

**Comment by alex-moc** [comment]
This pull request will have conflicts with #158. It contains only updated pods and can be ignored in this SDK.

**Comment by Clark73** [comment]
Thats fine,  this branch still needs to be fixed before we can merge it. And It sounds like #158 should  be merged first based on what you are saying?

**Comment by alex-moc** [comment]
Yes, #158 should be merged first

**Comment by Clark73** [comment]
@alex-moc Can you update this PR to resolve the conflicts and fix the build?

**Comment by alex-moc** [comment]
@Clark73 How I can to see the log /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/carthage-xcodebuild.rh2mqy.log? Local build has finished successful.

**Comment by alex-moc** [comment]
@Clark73 Current build system use Xcode 8.3.3
I use Xcode 9.2 for development. Next my tasks connected with upgrade project to iOS 11 and Xcode 9. It is time for upgrade xCode at Travis CI.

**Pull request closed without merging**
